//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoP2PrecoCombustivel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ESTADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ESTADO()
        {
            this.TB_ESTADO_COMBUSTIVEL = new HashSet<TB_ESTADO_COMBUSTIVEL>();
            this.TB_MELHOR_COMBUSTIVEL_VALOR = new HashSet<TB_MELHOR_COMBUSTIVEL_VALOR>();
        }
    
        public int ID { get; set; }
        public string nomeEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ESTADO_COMBUSTIVEL> TB_ESTADO_COMBUSTIVEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MELHOR_COMBUSTIVEL_VALOR> TB_MELHOR_COMBUSTIVEL_VALOR { get; set; }
    }
}
